projet_mi5/src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandeRepository")
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_commande;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statut;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LigneCommande", mappedBy="commande")
     */
    private $ligneCommandes;

    public function __construct()
    {
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeInterface $date_commande): self
    {
        $this->date_commande = $date_commande;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|LigneCommande[]
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setCommande($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes->removeElement($ligneCommande);
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getCommande() === $this) {
                $ligneCommande->setCommande(null);
            }
        }

        return $this;
    }
}

projet_mi5/src/Controller/PanierController.php
<?php
namespace App\Controller;
use App\Entity\Commande;
use App\Entity\Produit;
use App\Entity\User;
use App\Service\BoutiqueService;
use App\Service\PanierService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
class PanierController extends AbstractController
{

    public function index(PanierService $panierService)
    {
        $em = $this->getDoctrine()->getManager();
        $repo = $em->getRepository(Produit::class);
        $panierWithItems = [];
        $panier          = $panierService->getContenu();
        $prixTotal       = $panierService->getTotal();
        foreach ($panier as $id => $quantity) {
            $panierWithItems[] = ['item' =>$repo->find($id), 'quantity' => $quantity];
        }
        return $this->render(
            'panier/index.html.twig',
            [
                "panier" => $panierWithItems,
                "prix"   => $prixTotal,
            ]
        );

    }

    public function ajoutPanier(PanierService $panierService, $idProduit)
    {
        $panierService->ajouterProduit($idProduit);
        return $this->redirectToRoute('panier_page');
    }
    public function panierEnlever(PanierService $panierService, $idProduit)
    {
        $panierService->enleverProduit($idProduit);
        return $this->redirectToRoute('panier_page');
    }
    public function panierSupprimer(PanierService $panierService, $idProduit)
    {
        $panierService->supprimerProduit($idProduit);
        return $this->redirectToRoute('panier_page');
    }

    public function panierVider(PanierService $panierService)
    {
        $panierService->removeall();
        return $this->redirectToRoute('panier_page');
    }

    public function validation(PanierService $panierService){
        if($panierService->getNbProduits() == 0){
            return $this->render( 'panier/validation-empty.html.twig');
        }
        if($this->getUser()){
            $commandes = $this->getDoctrine()->getRepository(Commande::class)->findBy(['user' => $this->getUser()->getId()]);
            $commande = $panierService->panierToCommande($this->getUser());
            return $this->render( 'panier/validation.html.twig',[
                'user' => $this->getUser(),
                'commandes' => $commandes,
                'commande' => $commande
            ]);
        } else{
            return $this->redirectToRoute( 'app_login');
        }

    }

    public function iconePanier(PanierService $panierService){
            return $this->render('iconePanier.html.twig',[
                'articles'=>$panierService->getNbProduits()
            ]);
    }



}

projet_mi5/templates/panier/index.html.twig
{% extends "base.html.twig" %}
{% block content %}
<main role="main" class="container">
    <h1>Panier</h1>
    <div class="row">
        <div class="alert alert-dark col-md-12">
            <h1>
                <i class="fas fa-shopping-cart"></i> produit(s) : <b>{{ prix }} €</b>
            </h1>
            <div class="col-md-12 btn-group btn-group-lg" role="group">
                <a class="btn btn-secondary" href="{{ path ('boutique_page') }}">
                    Continuer les Courses
                </a>
                {% if panier is not empty %}
                <a class="btn btn-primary" href="{{ path ('panier_validation') }}">
                    Passer la Commande
                </a>
                {% endif %}
                <a class="btn btn-danger" href="{{ path ('panier.vider') }}">
                    Vider le panier
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        {% if panier is not empty %}
        <table class="table table-striped table-sm table-hover">
            <thead>
            <tr>
                <th></th>
                <th>Produit</th>
                <th>Quantite</th>
                <th>Prix</th>
                <th>Total</th>
                <th>Supprimer</th>
            </tr>
            </thead>
            <tbody>
            {% for item in panier %}
            {% set product = item['item'] %}
            {% set quantity = item['quantity'] %}
            <tr>
                <td>
                    <div class="col-4">
                        <div class="card clickable" style="width: 5rem;" >
                            <img src="{{ asset(product.visuel) }}" class="card-img-top" alt="Fruits">
                        </div>
                    </div>
                </td>
                <td>
                    <h4 class="card-title" >{{ product.libelle }}</h4>
                </td>
                <td>
                    <a href="{{ path('panier_enlever', {idProduit: product.id}) }}">
                        <i class="fa fa-minus mr-2"></i>
                    </a>
                    {{ quantity }}
                    <a href="{{ path('panier_ajouter', {idProduit: product.id}) }}">
                        <i class="fa fa-plus ml-2"></i>
                    </a>
                </td>
                <td>
                {{ product.prix }}€
                </td>
                <td>
                    {{product.prix * quantity }}€
                </td>
                <td>
                    <a href="{{ path('panier_supprimer', {idProduit: product.id}) }}">
                        <i class="fas fa-trash text-muted"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
            <thead>
            <tr>
                <th class="text-right" colspan="4">Total</th>
                <th class="text-right">{{prix}}€</th>
            </tr>
            </thead>
        </table>
    </div>
</main>
    {% endif %}
{% endblock %}

projet_mi5/templates/panier/validation-empty.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container">
        <p>Votre panier est vide !</p>
    </div>


{% endblock %}

projet_mi5/templates/panier/validation.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container">
        <h1>Merci pour votre commande</h1><hr>
        <h2>{{ user.Prenom }} {{ user.nom }}</h2>
        <p>Voici votre n° de commande : #{{ commande.id }}</p>
        <p>{{ commande.dateCommande | date }}</p>
        <a href="{{ path('commande') }}">Accéder à Mes commandes</a>
    </div>
{% endblock %}